/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;
import javax.swing.JFrame;
import java.io.File;
import java.util.HashMap;
import java.util.Map;
import javax.swing.JOptionPane;

import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.design.JasperDesign;
import net.sf.jasperreports.engine.xml.JRXmlLoader;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author ASUS
 */
public class FMenu extends javax.swing.JFrame {
    public static String levelUser;
    
    //deklarasi variabel
    Map param = new HashMap();
    //deklarasikan variabel untuk memanggil laporan
    JasperReport jasRep;
    JasperPrint jasPrint;
    JasperDesign jasDes;

    /**
     * Creates new form FrameMenu
     */
    public FMenu() {
        initComponents();
        loginGagal();
        //method tanggal
        setTanggal();
    }
    
    
    //buat method tanggal
    public void setTanggal() {
        java.util.Date skrng = new java.util.Date();
        java.text.SimpleDateFormat kal = new java.text.SimpleDateFormat
                                                       ("dd-MM-yyyy");
        java.text.SimpleDateFormat kalinput = new java.text.SimpleDateFormat
                                                        ("yyyy-MM-dd");
        lTanggal.setText (kal.format(skrng));
    }
    
    
    public static void loginGagal() {
        mnKelola.setVisible(false);
        mnTransaksi.setVisible(false);
        mnHistory.setVisible(false);
        smLogin.setText("Login");
    }
    
    public static void loginSukses() {
        //akses Admin
        mnKelola.setVisible(true);
        mnTransaksi.setVisible(false);
        mnHistory.setVisible(true);
        smGenLaporan.setVisible(true);
        
        if (levelUser.equals("petugas")) {
            //akses petugas
            mnKelola.setVisible(false);
            smGenLaporan.setVisible(true);
        }
        
        if (levelUser.equals("kasir")) {
            //akses siswa
            mnKelola.setVisible(false);
            mnTransaksi.setVisible(true);
            smGenLaporan.setVisible(true);
        }
        smLogin.setText("Logout");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lTanggal = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        mnUtilitas = new javax.swing.JMenu();
        smLogin = new javax.swing.JMenuItem();
        smKeluar = new javax.swing.JMenuItem();
        mnKelola = new javax.swing.JMenu();
        smSuplemen = new javax.swing.JMenuItem();
        smJenis = new javax.swing.JMenuItem();
        smSupplier = new javax.swing.JMenuItem();
        smPengguna = new javax.swing.JMenuItem();
        mnTransaksi = new javax.swing.JMenu();
        smEntrySPP = new javax.swing.JMenuItem();
        mnHistory = new javax.swing.JMenu();
        smGenLaporan = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));

        lTanggal.setText("dd/mm/yyyy");

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel1.setText("Tanggal");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(648, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(lTanggal)
                .addGap(53, 53, 53))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(471, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lTanggal)
                    .addComponent(jLabel1))
                .addGap(24, 24, 24))
        );

        jMenuBar1.setBackground(new java.awt.Color(251, 249, 249));
        jMenuBar1.setForeground(new java.awt.Color(204, 204, 255));

        mnUtilitas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/user (1).png"))); // NOI18N
        mnUtilitas.setText("Utilitas");

        smLogin.setText("Login");
        smLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                smLoginActionPerformed(evt);
            }
        });
        mnUtilitas.add(smLogin);

        smKeluar.setText("Keluar");
        smKeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                smKeluarActionPerformed(evt);
            }
        });
        mnUtilitas.add(smKeluar);

        jMenuBar1.add(mnUtilitas);

        mnKelola.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/healthcare (1).png"))); // NOI18N
        mnKelola.setText("Kelola Data");

        smSuplemen.setText("Data Suplemen");
        smSuplemen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                smSuplemenActionPerformed(evt);
            }
        });
        mnKelola.add(smSuplemen);

        smJenis.setText("Data Jenis");
        smJenis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                smJenisActionPerformed(evt);
            }
        });
        mnKelola.add(smJenis);

        smSupplier.setText("Data Supplier");
        smSupplier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                smSupplierActionPerformed(evt);
            }
        });
        mnKelola.add(smSupplier);

        smPengguna.setText("Data Pengguna");
        smPengguna.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                smPenggunaActionPerformed(evt);
            }
        });
        mnKelola.add(smPengguna);

        jMenuBar1.add(mnKelola);

        mnTransaksi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/treatment (1).png"))); // NOI18N
        mnTransaksi.setText("Transaksi");

        smEntrySPP.setText("Entry Pembayaran");
        smEntrySPP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                smEntrySPPActionPerformed(evt);
            }
        });
        mnTransaksi.add(smEntrySPP);

        jMenuBar1.add(mnTransaksi);

        mnHistory.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/report (1).png"))); // NOI18N
        mnHistory.setText("History");

        smGenLaporan.setText("Generate Laporan");
        smGenLaporan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                smGenLaporanActionPerformed(evt);
            }
        });
        mnHistory.add(smGenLaporan);

        jMenuBar1.add(mnHistory);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void smJenisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_smJenisActionPerformed
        // TODO add your handling code here:
        FJenis a = new FJenis();
        a.setVisible(true);
    }//GEN-LAST:event_smJenisActionPerformed

    private void smLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_smLoginActionPerformed
        if ("Login".equals(FMenu.smLogin.getText())) {
            FLogin login = new FLogin();
            login.setVisible(true);
        }
        else {
            FMenu.loginGagal();
        }
    }//GEN-LAST:event_smLoginActionPerformed

    private void smKeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_smKeluarActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_smKeluarActionPerformed

    private void smSuplemenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_smSuplemenActionPerformed
        // TODO add your handling code here:
        FSuplemen a = new FSuplemen();
        a.setVisible(true);
    }//GEN-LAST:event_smSuplemenActionPerformed

    private void smSupplierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_smSupplierActionPerformed
        // TODO add your handling code here:
        FSupplier a = new FSupplier();
        a.setVisible(true);
    }//GEN-LAST:event_smSupplierActionPerformed

    private void smPenggunaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_smPenggunaActionPerformed
        // TODO add your handling code here:
        FUser a = new FUser();
        a.setVisible(true);
    }//GEN-LAST:event_smPenggunaActionPerformed

    private void smEntrySPPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_smEntrySPPActionPerformed
        // TODO add your handling code here:
        FBayarSPP a = new FBayarSPP();
        a.setVisible(true);
    }//GEN-LAST:event_smEntrySPPActionPerformed

    private void smGenLaporanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_smGenLaporanActionPerformed
        // TODO add your handling code here:
        try {
    File report = new File("src/report/LaporanPenjualan.jrxml");
    jasDes = JRXmlLoader.load(report);
    jasRep = JasperCompileManager.compileReport(jasDes);
    jasPrint = JasperFillManager.fillReport(jasRep, null, koneksi.koneksi.getConnection());
    JasperViewer.viewReport(jasPrint, false);
} catch (Exception e) {
    JOptionPane.showMessageDialog(null, "Gagal Membuka Laporan", "Cetak Laporan", 
        JOptionPane.ERROR_MESSAGE);
}

    }//GEN-LAST:event_smGenLaporanActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lTanggal;
    private static javax.swing.JMenu mnHistory;
    private static javax.swing.JMenu mnKelola;
    private static javax.swing.JMenu mnTransaksi;
    private javax.swing.JMenu mnUtilitas;
    private static javax.swing.JMenuItem smEntrySPP;
    private static javax.swing.JMenuItem smGenLaporan;
    private static javax.swing.JMenuItem smJenis;
    private javax.swing.JMenuItem smKeluar;
    private static javax.swing.JMenuItem smLogin;
    private static javax.swing.JMenuItem smPengguna;
    private static javax.swing.JMenuItem smSuplemen;
    private static javax.swing.JMenuItem smSupplier;
    // End of variables declaration//GEN-END:variables
}
